// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("YC.QuickGraph.Query")>]
[<assembly: AssemblyProductAttribute("YC.QuickGraph.Query")>]
[<assembly: AssemblyDescriptionAttribute("Path query engine for QuickGraph")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] Version = "1.0"
    let [<Literal>] InformationalVersion = "1.0"
